---

- name: Configure apt repository
  when:
    - ansible_pkg_mgr in [ "apt" ]
  block:
    - name: Import apt key
      ansible.builtin.apt_key:
        url: "{{ item }}"
        state: present
      loop: "{{ virtualbox_keys }}"
      loop_control:
        label: "{{ item | basename }}"

    - name: Place apt repository
      ansible.builtin.apt_repository:
        repo: deb [ arch=amd64 ] {{ virtualbox_apt_repository }} {{ ansible_distribution_release | lower }} contrib
        state: present

- name: Install requirements
  ansible.builtin.package:
    name: "{{ virtualbox_requirements }}"
    state: present

- name: Install virtualbox
  ansible.builtin.package:
    name: "{{ virtualbox_package }}"
    state: present
  notify:
    - Run vboxconfig
