---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: virtaulbox
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:${TAG:-latest}"
    cgroupns_mode: host
    command: ${DOCKER_COMMAND:-""}
    override_command: false
    privileged: true
    pre_build_image: true
    user: 0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 3
  playbooks:
    converge: "${MOLECULE_PLAYBOOK:-converge.yml}"
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
